// generated by the following code:
//
// require('gradient-string')([
//   { color: '#03a9f4', pos: 0 },
//   { color: '#03a9f4', pos: 0.1 },
//   { color: '#647eff', pos: 1 }
// ])('Kdu.js - The Progressive JavaScript Framework'))
//
// Use the output directly here to keep the bundle small.

const banner =
  '\x1B[38;2;3;169;244mK\x1B[39m\x1B[38;2;3;169;244md\x1B[39m\x1B[38;2;3;169;244mu\x1B[39m\x1B[38;2;3;169;244m.\x1B[39m\x1B[38;2;3;169;244mj\x1B[39m\x1B[38;2;3;169;244ms\x1B[39m \x1B[38;2;3;169;244m-\x1B[39m \x1B[38;2;3;169;244mT\x1B[39m\x1B[38;2;0;166;247mh\x1B[39m\x1B[38;2;0;166;247me\x1B[39m \x1B[38;2;0;166;247mK\x1B[39m\x1B[38;2;0;163;249md\x1B[39m\x1B[38;2;0;163;249mu\x1B[39m \x1B[38;2;0;160;251mF\x1B[39m\x1B[38;2;0;160;251mr\x1B[39m\x1B[38;2;54;145;255ma\x1B[39m\x1B[38;2;54;145;255mm\x1B[39m\x1B[38;2;78;136;255me\x1B[39m\x1B[38;2;78;136;255mw\x1B[39m\x1B[38;2;100;126;255mo\x1B[39m\x1B[38;2;100;126;255mr\x1B[39m\x1B[38;2;100;126;255mk\x1B[39m'

export default banner
